#!/bin/bash
apt update;
apt-get install python3 -y;
apt-get install python3-pip -y;
pip3 install flask


cd /usr/bin/
rm -rf add-wstr
rm -rf add-wsnone
rm -rf add-wsstb
rm -rf add-trl
rm -rf add-trnone
rm -rf add-trstb
rm -rf backend
cd
mkdir -p /root/back
cd /root/back
wget -q https://github.com/jsjsjsjsjsjsjsjsjsjsjsjs/hayomauapa/raw/main/mek.zip
wget -q https://github.com/jsjsjsjsjsjsjsjsjsjsjsjs/hayomauapa/raw/main/backend
unzip mek.zip
chmod +x *
mv * /usr/bin/
sed -i -e 's/\r$//' /usr/bin/add-trl
sed -i -e 's/\r$//' /usr/bin/add-trnone
sed -i -e 's/\r$//' /usr/bin/add-trstb
sed -i -e 's/\r$//' /usr/bin/add-wsnone
sed -i -e 's/\r$//' /usr/bin/add-wsstb
sed -i -e 's/\r$//' /usr/bin/add-wstr
cd
rm -rf /root/back

cat >/etc/systemd/system/backend.service << EOF
[Unit]
Description=My Project
After=network.target

[Service]
WorkingDirectory=/root
ExecStart=/usr/bin/python3 /usr/bin/backend 0.0.0.0 meki
Restart=always

[Install]
WantedBy=multi-user.target
EOF
systemctl daemon-reload
systemctl restart backend
systemctl enable backend
systemctl restart systemd-hostnamed >/dev/null 2>&1
